In [ ]:
import random
import pandas as pd

In [ ]:
cities=[ "New York", "London", "Tokyo", "Paris", "Sydney",
    "Dubai", "Singapore", "Los Angeles", "Toronto", "Berlin",
    "Rome", "Barcelona", "Moscow", "Mumbai", "Cape Town",
    "Bangkok", "Istanbul", "Chicago", "Hong Kong", "Amsterdam"
]

In [ ]:

air_india=[random.randint(10000,50000)for _ in range(20)]
spice_jet=[random.randint(20000,45000)for _ in range(20)]
boing_india=[random.randint(12000,90000)for _ in range(20)]
emritates=[random.randint(20000,70000)for _ in range(20)]
go_airlines=[random.randint(10000,50000)for _ in range(20)]
travel={'cities':cities,
        'air_india':air_india,
        'spice_jet':spice_jet,
        'boing_india':boing_india,
        'emritates':emritates,
        'go_airlines':go_airlines}

In [ ]:
data=pd.DataFrame(travel)
data

         cities  air_india  spice_jet  boing_india  emritates  go_airlines
0      New York      11016      41978        69193      21506        27521
1        London      20281      22496        67629      51345        10636
2         Tokyo      33831      28113        83305      26131        20714
3         Paris      35016      37042        69352      60974        42543
4        Sydney      11689      20306        51098      29677        45249
5         Dubai      41136      22298        50425      49985        49195
6     Singapore      37561      32395        20291      50803        47338
7   Los Angeles      23160      40951        89108      65219        14731
8       Toronto      33545      42819        64838      22309        19016
9        Berlin      12578      41904        68243      27458        19854
10         Rome      22920      31869        62903      34627        44463
11    Barcelona      23412      43111        64668      37323        37005
12       Moscow      20732      28604        25262      59887        34046
13       Mumbai      48873      39851        72585      36384        23672
14    Cape Town      16377      24131        25849      28427        26426
15      Bangkok      13078      30704        86807      20416        18504
16     Istanbul      11233      43866        62183      54078        42955
17      Chicago      49488      37955        59512      20749        26179
18    Hong Kong      35883      20148        52432      42988        24183
19    Amsterdam      26120      34302        75345      57858        18573

In [ ]:

import pandas as pd
import random
students=["aditya","anuj","ishant","nayan","suhani","muskan","komal","nidhi","varun","tushar","ajay","jaspreet","harvinder","jasvinder","naresh"]
science=[random.randint(50,100) for _ in range(len(students))]
maths=[random.randint(40,90)for _ in range(len(students))]
sst=[random.randint(50,95)for _ in range(len(students))]
hindi=[random.randint(50,95)for _ in range(len(students))]
computer=[random.randint(50,95)for _ in range(len(students))]
stud={"students":students,"science":science,"sst":sst,"maths":maths,"hindi":hindi,"computer":computer}
data=pd.DataFrame(stud)
data.head(4)
list(data.students)
data.tail(7)

     students  science  sst  maths  hindi  computer
8       varun       92   94     42     56        83
9      tushar       77   66     86     82        60
10       ajay       76   88     71     52        62
11   jaspreet       88   95     90     63        89
12  harvinder       78   53     58     58        75
13  jasvinder       80   80     79     76        68
14     naresh       86   89     44     56        89