In [ ]:
from google.colab import files
files.upload()

In [ ]:
!mkdir -p ~/.kaggle

In [ ]:
!cp /content/kaggle.json ~/.kaggle

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d srisyra02/house-price-prediction-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/srisyra02/house-price-prediction-dataset
License(s): CC0-1.0
Downloading house-price-prediction-dataset.zip to /content
100% 7.50M/7.50M [00:00<00:00, 115MB/s]

In [ ]:
!unzip house-price-prediction-dataset.zip

Archive:  house-price-prediction-dataset.zip
  inflating: indian_house_price_prediction_data.csv

In [ ]:
import pandas as pd
data=pd.read_csv('/content/indian_house_price_prediction_data.csv')
data

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249996,249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249997,249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249998,249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
249999,250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [ ]:
data.head(20)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move
5,6,West Bengal,Durgapur,Locality_246,Apartment,4,3500,135.28,0.04,2020,...,5,7,7,Low,Yes,Yes,"Playground, Clubhouse",West,Broker,Ready_to_Move
6,7,Tamil Nadu,Coimbatore,Locality_254,Independent House,3,4826,318.12,0.07,2016,...,9,3,6,High,No,Yes,"Clubhouse, Garden, Playground",North,Builder,Under_Construction
7,8,Chhattisgarh,Bilaspur,Locality_490,Independent House,5,4252,141.39,0.03,2021,...,4,10,10,High,Yes,Yes,"Gym, Pool, Clubhouse, Playground",North,Builder,Under_Construction
8,9,Delhi,New Delhi,Locality_232,Villa,4,2678,189.16,0.07,2003,...,22,7,5,Low,No,Yes,"Garden, Clubhouse, Playground",South,Broker,Under_Construction
9,10,Jharkhand,Ranchi,Locality_122,Villa,2,1393,187.42,0.13,2011,...,14,3,3,High,Yes,No,"Clubhouse, Playground, Garden, Gym",East,Owner,Ready_to_Move
10,11,Telangana,Warangal,Locality_75,Independent House,1,665,324.24,0.49,1991,...,34,1,8,Low,No,Yes,Clubhouse,North,Broker,Under_Construction
11,12,Karnataka,Bangalore,Locality_462,Apartment,5,3988,465.38,0.12,2022,...,3,6,4,High,No,Yes,"Clubhouse, Pool, Playground, Gym",West,Broker,Ready_to_Move
12,13,Maharashtra,Nagpur,Locality_227,Independent House,3,1976,486.29,0.25,2020,...,5,6,6,Medium,No,Yes,"Clubhouse, Gym, Playground, Pool",North,Builder,Ready_to_Move
13,14,Delhi,New Delhi,Locality_287,Independent House,1,1369,309.82,0.23,2013,...,12,10,6,Medium,No,No,"Clubhouse, Garden, Gym, Playground, Pool",South,Broker,Under_Construction
14,15,Uttar Pradesh,Lucknow,Locality_148,Apartment,2,3852,77.62,0.02,2006,...,19,8,3,Medium,No,No,"Garden, Gym, Playground",East,Broker,Ready_to_Move
15,16,Rajasthan,Jaipur,Locality_369,Apartment,1,2815,491.97,0.17,2015,...,10,9,6,High,Yes,Yes,Playground,East,Owner,Under_Construction
16,17,Assam,Silchar,Locality_265,Villa,5,1250,75.23,0.06,1993,...,32,1,8,Medium,No,No,"Pool, Playground, Garden, Gym",South,Builder,Under_Construction
17,18,Uttarakhand,Dehradun,Locality_50,Villa,1,3518,234.99,0.07,2004,...,21,8,1,High,No,Yes,"Pool, Clubhouse, Gym",West,Builder,Ready_to_Move
18,19,Maharashtra,Pune,Locality_385,Villa,3,2126,24.50,0.01,2013,...,12,8,1,Low,No,Yes,"Garden, Clubhouse, Pool, Gym, Playground",West,Owner,Under_Construction
19,20,Chhattisgarh,Bilaspur,Locality_241,Villa,2,2524,407.96,0.16,2016,...,9,8,6,High,Yes,No,"Pool, Playground, Clubhouse",North,Broker,Under_Construction

In [ ]:
data.tail(100)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
249900,249901,Tamil Nadu,Chennai,Locality_303,Apartment,3,4221,391.09,0.09,1991,...,34,9,7,High,No,No,"Garden, Pool, Clubhouse, Playground, Gym",North,Broker,Under_Construction
249901,249902,Gujarat,Surat,Locality_32,Independent House,3,1146,445.16,0.39,2002,...,23,1,2,Medium,Yes,Yes,"Pool, Gym, Clubhouse, Playground, Garden",East,Builder,Ready_to_Move
249902,249903,Gujarat,Ahmedabad,Locality_330,Independent House,5,2203,33.56,0.02,2010,...,15,1,10,Low,Yes,Yes,"Pool, Gym",East,Broker,Ready_to_Move
249903,249904,Haryana,Faridabad,Locality_244,Villa,1,3768,173.46,0.05,2013,...,12,5,3,Medium,Yes,Yes,"Gym, Garden, Clubhouse, Pool",East,Owner,Under_Construction
249904,249905,Tamil Nadu,Chennai,Locality_348,Apartment,2,4856,254.84,0.05,2013,...,12,5,10,Low,Yes,Yes,"Clubhouse, Pool",West,Builder,Under_Construction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249996,249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249997,249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249998,249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
249999,250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

In [ ]:
data.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,125000.500000,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016
std,72168.927986,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860
min,1.000000,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,62500.750000,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,125000.500000,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000
75%,187500.250000,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,250000.000000,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

In [ ]:
data.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='object')

In [ ]:
import numpy as np
a=np.unique(np.array(data['BHK']))
c=np.where(data['BHK']>4)
z=np.mean(data['Price_per_SqFt'])
y=np.sum(data['BHK'])
z
type(len(c))
y
data['Price_per_SqFt']!=0

0         True
1         True
2         True
3         True
4         True
          ...
249995    True
249996    True
249997    True
249998    True
249999    True
Name: Price_per_SqFt, Length: 250000, dtype: bool

In [ ]:
data['State']=='Haryana'
c=np.where(data['State']=='Punjab')
len(c)

1

In [ ]:
data.isnull()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
delhi = data['City']=='Delhi'
print(delhi)

0         False
1         False
2         False
3         False
4         False
          ...
249995    False
249996    False
249997    False
249998    False
249999    False
Name: City, Length: 250000, dtype: bool

In [ ]:
data['BHK'] %2!=0
data['BHK']

0         1
1         3
2         2
3         2
4         4
         ..
249995    5
249996    1
249997    4
249998    1
249999    3
Name: BHK, Length: 250000, dtype: int64

In [ ]:
np.amax(data['Price_per_SqFt'])

0.99

In [ ]:
np.var(data['Price_per_SqFt'])

0.017094773429773263

In [ ]:
np.max(data['Size_in_SqFt'])

5000

In [ ]:
np.max(data['BHK'])

5

In [ ]:
np.cov(data['Size_in_SqFt'])

array(1691578.44815353)

In [ ]:
np.common_type(data['Price_per_SqFt'])

numpy.float64

In [ ]:

l=list(data['State'])
a=list(data['City'])
c=l.count('Haryana')
b=a.count('Chennai')
print(c)
print(b)

12314
6168

KeyError: 'Locatity'